Flowpack:
  Photon:
    Fusion:

      fusion:

        autoInclude:
          Neos.Fusion: true
          Flowpack.Photon.Fusion: true

Neos:
  Fusion:
    rendering:
      exceptionHandler: 'Neos\Fusion\Core\ExceptionHandlers\BubblingHandler'

    defaultContext:
      'Photon.Slug': 'Flowpack\Photon\Fusion\Eel\SlugHelper'
      'Photon.Debug': 'Flowpack\Photon\Fusion\Eel\DebugHelper'
