Flowpack:
  Photon:
    Fusion:

      fusion:

        autoInclude:
          Neos.Fusion: true
          Flowpack.Photon.Fusion: true

  Fusion:
    rendering:
      exceptionHandler: 'Neos\Fusion\Core\ExceptionHandlers\BubblingHandler'
